easy_admin:
    site_name: 'Nakade <img width="64px" height="64px" alt="Nakade" src="/images/nakade_256x256.png" /> Admin'
    formats:
        date:     'd-m-Y'
        time:     'H:i'
        datetime: 'd-m-Y'
    user:
        display_name: true
        display_avatar: true
        avatar_property_path: 'avatarUrl'
    design:
        assets:
            favicon: '/images/nakade_256x256.png'
        brand_color: '#1ABC9C'
        menu:
          - { entity: User, default: true, label: 'easyAdmin.user', icon: 'users'}
          - { entity: ContactMail, label: 'easyAdmin.contact', icon: 'inbox'}
          - { entity: Quotes, label: 'easyAdmin.quotes', icon: 'pencil-square-o'}
          - { entity: NewsReader, label: 'easyAdmin.news.reader', icon: 'address-card-o'}
          - { entity: NewsLetter, label: 'easyAdmin.news.letter', icon: 'envelope-o'}
          - { label: 'easyAdmin.placeholder'}
          - { entity: Feature, label: 'easyAdmin.feature.title', icon: 'plus-square-o'}
          - { entity: BugReport, label: 'easyAdmin.bug.title', icon: 'bug'}
          - { label: 'easyAdmin.placeholder'}
          - { label: 'PHP Info', route: easyadmin_phpinfo, icon: 'info' }
          - { label: 'easyAdmin.exit', route: 'app_homepage', icon: 'home'}
    list:
        actions:
            - { name: show, icon: search, label: false, title: 'easyAdmin.update' }
            - { name: edit, icon: pencil, label: false, title: 'easyAdmin.update' }
            - { name: delete, icon: remove, label: false, title: 'easyAdmin.delete' }
    entities:
#        # List the entity class name you want to manage
        Quotes:
            class: App\Entity\Quotes
            label: 'easyAdmin.quotes'
            list:
                fields: [
                   { property: 'id', label: 'easyAdmin.id' },
                   { property: 'quote', label: 'easyAdmin.quote.quote' },
                   { property: 'details', label: 'easyAdmin.quote.origin' },
                   { property: 'createdAt', label: 'easyAdmin.createdAt' },
                   ]
            search:
                fields: ['quote', 'details']
            form:
                fields:
                  - { property: 'quote', type: 'text_editor', label: 'easyAdmin.quote.quote' }
                  - { property: 'details', label: 'easyAdmin.quote.origin' }
        ContactMail:
            class: App\Entity\ContactMail
            label: 'easyAdmin.contact'
            help: 'easyAdmin.contact.help'
            templates:
                list: 'admin/contact/list.html.twig'
            list:
                actions: [-new, -edit,]
                fields: [
                    { property: 'id', label: 'easyAdmin.user.id' },
                    { property: 'email', type: 'email', label: 'easyAdmin.user.email' },
                    { property: 'name', label: 'easyAdmin.user.name' },
                    { property: 'phone', label: 'easyAdmin.contact.phone' },
                    { property: 'zipCode', label: 'easyAdmin.contact.zip' },
                    { property: 'city', label: 'easyAdmin.contact.city' },
                    { property: 'address', label: 'easyAdmin.contact.address' },
                    { property: 'createdAt', label: 'easyAdmin.createdAt' },
                    ]
                sort: ['createdAt', 'DESC']
            search:
                fields: ['email', 'firstName', 'lastName', 'message']
            show:
                actions: [-edit]
                fields:
                  - { property: 'email', label: 'easyAdmin.user.email' }
                  - { property: 'name', type: 'text', label: 'easyAdmin.user.name' }
                  - { property: 'phone', label: 'easyAdmin.contact.phone'}
                  - { property: 'zipCode', label: 'easyAdmin.contact.zip' }
                  - { property: 'city', label: 'easyAdmin.contact.city' }
                  - { property: 'address', label: 'easyAdmin.contact.address' }
                  - { property: 'createdAt', label: 'easyAdmin.createdAt' }
                  - { property: 'message', label: 'easyAdmin.message' }
        User:
            class: App\Entity\User
            label: 'easyAdmin.user'
            search:
                fields: ['email', 'fullName', 'id', 'nickName']
            templates:
                list: 'admin/user/list.html.twig'
                edit: 'admin/user/edit.html.twig'
            edit:
                actions: [-delete]
            list:
                filters:
                  - { property: 'roles', type: 'App\Form\Filter\RoleFilterType' }
                  - { property: 'confirmed' }
                  - { property: 'disabled' }
                  - { property: 'locked' }
                actions: ['-delete', '-new', '-show']
                fields: [
                    { property: 'id', label: 'easyAdmin.user.id' },
                    { property: 'email', type: 'email', label: 'easyAdmin.user.email' },
                    { property: 'fullName', label: 'easyAdmin.user.name' },
                    { property: 'nickName', label: 'easyAdmin.user.nick' },
                    { property: 'roles', label: 'easyAdmin.user.role'},
                    { property: 'avatarUrl', type: 'image', label: 'easyAdmin.user.avatar', sortable: false },
                    { property: 'disabled', label: 'easyAdmin.user.disabled' },
                    { property: 'locked', label: 'easyAdmin.user.locked' },
                    { property: 'confirmed', help: 'Email Adresse ist bestätigt.', label: 'easyAdmin.user.confirmed' },
                    { property: 'createdAt', label: 'easyAdmin.createdAt' },
                    ]
                sort: ['firstName', 'ASC']
            form:
                title: "easyAdmin.user.edit.title"
                fields:
                    - { property: 'fullName', type: 'text', type_options: { disabled: true } }
                    - { property: 'email', type_options: { disabled: true } }
        NewsReader:
            class: App\Entity\NewsReader
            label: 'easyAdmin.news.reader'
            help: 'easyAdmin.news.reader.help'
            search:
              fields: ['email', 'firstName', 'lastName']
            list:
                actions: [-show]
                filters: [ 'confirmed' ]
                fields:
                  - { property: 'id', label: 'easyAdmin.user.id' }
                  - { property: 'email', type: 'email', label: 'easyAdmin.user.email' }
                  - { property: 'firstName', label: 'easyAdmin.user.firstName' }
                  - { property: 'lastName', label: 'easyAdmin.user.lastName' }
                  - { property: 'confirmed', help: 'Email Adresse ist bestätigt.', label: 'easyAdmin.user.confirmed' }
                  - { property: 'createdAt', label: 'easyAdmin.createdAt' }
                sort: ['email', 'ASC']
            form:
                fields:
                  - { property: 'firstName', label: 'easyAdmin.user.firstName' }
                  - { property: 'lastName', label: 'easyAdmin.user.lastName' }
                  - { property: 'email', label: 'easyAdmin.user.email' }
                  - { property: 'confirmed', label: 'easyAdmin.user.confirmed' }
        NewsLetter:
            class: App\Entity\NewsLetter
            label: 'easyAdmin.news.letter'
            help: 'easyAdmin.news.letter.help'
            search:
                fields: ['dueAt']
            templates:
                list:  'admin/news/list.html.twig'
            list:
                actions: [-edit, -show]
                fields:
                  - { property: 'id', label: 'easyAdmin.user.id' }
                  - { property: 'dueAt', label: 'easyAdmin.news.letter.dueAt' }
                  - { property: 'sendAt', label: 'easyAdmin.news.letter.sendAt' }
                  - { property: 'NoRecipients', label: 'easyAdmin.news.letter.noRecipients' }
            form:
                fields:
                  - { property: 'dueAt', label: 'easyAdmin.user.firstName' }
                  - { property: 'sendAt', label: 'easyAdmin.user.lastName' }
                  - { property: 'NoRecipients', label: 'easyAdmin.user.email' }
        Feature:
            class: App\Entity\Feature
            label: 'easyAdmin.feature.title'
            help: 'easyAdmin.feature.help'
            templates:
                list:  'admin/feature/list.html.twig'
                new:  'admin/feature/new.html.twig'
                show:  'admin/feature/show.html.twig'
                field_association: 'admin/feature/field_association.html.twig'
            search:
                fields: ['message']
            list:
                fields:
                  - { property: 'id', label: 'easyAdmin.user.id' }
                  - { property: 'title', label: 'easyAdmin.feature.title' }
                  - { property: 'status', label: 'easyAdmin.feature.state' }
                  - { property: 'comments', label: 'easyAdmin.feature.comments' }
                  - { property: 'author', label: 'easyAdmin.feature.author' }
                  - { property: 'createdAt', label: 'easyAdmin.feature.createdAt' }
            form:
                fields:
                  - { property: 'title', label: 'easyAdmin.feature.title' }
                  - { property: 'message', label: 'easyAdmin.feature.message', type: 'text_editor' }
                  - { property: 'status',
                      label: 'easyAdmin.feature.state',
                      permission: 'ROLE_SUPER_ADMIN',
                      type: 'choice',
                      type_options: {
                        choices: {
                          'open': 'open',
                          'ongoing': 'ongoing',
                          'finished': 'finished',
                          'reopened': 'reopened',
                          'closed': 'closed',
                          'rejected': 'rejected'
                        }}
                    }
            show:
                actions: [-delete, -edit]
                fields:
                  - { property: 'message', label: 'easyAdmin.feature.message' }
                  - { property: 'status', label: 'easyAdmin.feature.state' }
                  - { property: 'comments', label: 'easyAdmin.feature.comments' }
                  - { property: 'author', label: 'easyAdmin.feature.author' }
                  - { property: 'createdAt', label: 'easyAdmin.feature.createdAt' }
            edit:
                actions: [-delete]
        BugReport:
            class: App\Entity\BugReport
            label: 'easyAdmin.bug.title'
            help: 'easyAdmin.bug.help'
            templates:
                list:  'admin/feature/list.html.twig'
                new:  'admin/feature/new.html.twig'
                show:  'admin/bug/show.html.twig'
                field_association: 'admin/feature/field_association.html.twig'
            search:
                fields: ['message']
            list:
                fields:
                  - { property: 'id', label: 'easyAdmin.user.id' }
                  - { property: 'title', label: 'easyAdmin.bug.title' }
                  - { property: 'priority', label: 'easyAdmin.bug.priority' }
                  - { property: 'status', label: 'easyAdmin.bug.state' }
                  - { property: 'comments', label: 'easyAdmin.bug.comments' }
                  - { property: 'author', label: 'easyAdmin.bug.author' }
                  - { property: 'createdAt', label: 'easyAdmin.bug.createdAt' }
            form:
                fields:
                  - { property: 'title', label: 'easyAdmin.bug.title' }
                  - { property: 'message', label: 'easyAdmin.bug.message', type: 'text_editor' }
                  - { property: 'priority',
                      label: 'easyAdmin.bug.priority',
                      type: 'choice',
                      type_options: {
                        choices: {
                          'low': 1,
                          'normal': 2,
                          'high': 3,
                        }}
                    }
                  - { property: 'status',
                      label: 'easyAdmin.bug.state',
                      permission: 'ROLE_SUPER_ADMIN',
                      type: 'choice',
                      type_options: {
                        choices: {
                          'open': 'open',
                          'ongoing': 'ongoing',
                          'finished': 'finished',
                          'reopened': 'reopened',
                          'closed': 'closed',
                          'rejected': 'rejected'
                        }}
                      }
            show:
                actions: [-delete, -edit]
                fields:
                  - { property: 'message', label: 'easyAdmin.bug.message' }
                  - { property: 'status', label: 'easyAdmin.bug.state' }
                  - { property: 'comments', label: 'easyAdmin.bug.comments' }
                  - { property: 'author', label: 'easyAdmin.bug.author' }
                  - { property: 'createdAt', label: 'easyAdmin.bug.createdAt' }
            edit:
                actions: [-delete]
