easy_admin:
    site_name: 'Nakade <img width="64px" height="64px" alt="Nakade" src="../images/nakade_256x256.png" /> Admin'
    formats:
        date:     'd-m-Y'
        time:     'H:i'
        datetime: 'd-m-Y'
    user:
        display_name: true
        display_avatar: true
        avatar_property_path: 'avatarUrl'
    design:
        brand_color: '#1ABC9C'
        menu:
          - { entity: User, default: true, label: 'easyAdmin.user', icon: 'users'}
          - 'ContactMail'
          - 'Quotes'
          - 'NewsReader'
          - 'NewsLetter'
          - { label: 'easyAdmin.placeholder'}
          - { label: 'easyAdmin.exit', route: 'app_homepage', icon: 'home'}
    list:
        actions:
            - { name: show, icon: search, label: false, title: 'easyAdmin.update' }
            - { name: edit, icon: pencil, label: false, title: 'easyAdmin.update' }
            - { name: delete, icon: remove, label: false, title: 'easyAdmin.delete' }
    entities:
#        # List the entity class name you want to manage
        Quotes:
            class: App\Entity\Common\Quotes
            label: 'easyAdmin.quotes'
            list:
                fields: [
                   { property: 'id', label: 'easyAdmin.id' },
                   { property: 'quote', label: 'easyAdmin.quote.quote' },
                   { property: 'details', label: 'easyAdmin.quote.origin' },
                   { property: 'createdAt', label: 'easyAdmin.createdAt' },
                   ]
            search:
                fields: ['quote', 'details']
        ContactMail:
            class: App\Entity\Common\ContactMail
            label: 'easyAdmin.contact'
            help: 'easyAdmin.contact.help'
            list:
                actions: [-new, -edit,]
                fields: [
                    { property: 'id', label: 'easyAdmin.user.id' },
                    { property: 'email', type: 'email', label: 'easyAdmin.user.email' },
                    { property: 'name', label: 'easyAdmin.user.name' },
                    { property: 'phone', label: 'easyAdmin.contact.phone' },
                    { property: 'zipCode', label: 'easyAdmin.contact.zip' },
                    { property: 'city', label: 'easyAdmin.contact.city' },
                    { property: 'address', label: 'easyAdmin.contact.address' },
                    { property: 'createdAt', label: 'easyAdmin.createdAt' },
                    ]
                sort: ['firstName', 'ASC']
            search:
                fields: ['email', 'firstName', 'lastName', 'message']
            show:
                fields:
                  - { property: 'email', label: 'easyAdmin.user.email' }
                  - { property: 'name', label: 'easyAdmin.user.name' }
                  - { property: 'phone', label: 'easyAdmin.contact.phone'}
                  - { property: 'zipCode', label: 'easyAdmin.contact.zip' }
                  - { property: 'city', label: 'easyAdmin.contact.city' }
                  - { property: 'address', label: 'easyAdmin.contact.address' }
                  - { property: 'createdAt', label: 'easyAdmin.createdAt' }
                  - { property: 'message', label: 'easyAdmin.message' }
        User:
            class: App\Entity\User
            label: 'easyAdmin.user'
            list:
                actions: [-show]
                fields: [
                    { property: 'id', label: 'easyAdmin.user.id' },
                    { property: 'email', type: 'email', label: 'easyAdmin.user.email' },
                    { property: 'fullName', label: 'easyAdmin.user.name' },
                    { property: 'nickName', label: 'easyAdmin.user.nick' },
                    { property: 'roles', label: 'easyAdmin.user.role'},
                    { property: 'avatarUrl', type: 'image', label: 'easyAdmin.user.avatar', sortable: false },
                    { property: 'disabled', label: 'easyAdmin.user.disabled' },
                    { property: 'locked', label: 'easyAdmin.user.locked' },
                    { property: 'confirmed', help: 'Email Adresse ist bestätigt.', label: 'easyAdmin.user.confirmed' },
                    { property: 'createdAt', label: 'easyAdmin.createdAt' },
                    { property: 'updatedAt', label: 'easyAdmin.updatedAt' },
                    ]
                sort: ['firstName', 'ASC']
            form:
                fields:
                    - { property: 'firstName', label: 'easyAdmin.user.firstName' }
                    - { property: 'lastName', label: 'easyAdmin.user.lastName' }
                    - { property: 'nickName', label: 'easyAdmin.user.nick' }
                    - { property: 'email', label: 'easyAdmin.user.email', help: 'easyAdmin.user.email.help', type_options: { disabled: true } }
                    - { property: 'password', label: 'easyAdmin.user.password', type_options: { disabled: true } }
                    -
                       property: 'roles'
                       permission: ROLE_ADMIN
                       type: 'choice'
                       label: 'easyAdmin.user.role'
                       help: 'easyAdmin.user.role.help'
                       type_options:
                          mapped: true
                          expanded: true
                          multiple: true
                          choices:
                            - { 'easyAdmin.user.role.member': 'ROLE_MEMBER' }
                            - { 'easyAdmin.user.role.admin':  'ROLE_ADMIN' }
        NewsReader:
            class: App\Entity\NewsReader
            label: 'NewsReader'
            list:
                actions: [-show]
                fields:
                  - { property: 'id', label: 'easyAdmin.user.id' }
                  - { property: 'email', type: 'email', label: 'easyAdmin.user.email' }
                  - { property: 'firstName', label: 'easyAdmin.user.firstName' }
                  - { property: 'lastName', label: 'easyAdmin.user.lastName' }
                  - { property: 'confirmed', help: 'Email Adresse ist bestätigt.', label: 'easyAdmin.user.confirmed' }
                  - { property: 'createdAt', label: 'easyAdmin.createdAt' }
                sort: ['email', 'ASC']
            form:
                fields:
                  - { property: 'firstName', label: 'easyAdmin.user.firstName' }
                  - { property: 'lastName', label: 'easyAdmin.user.lastName' }
                  - { property: 'email', label: 'easyAdmin.user.email' }
                  - { property: 'confirmed', label: 'easyAdmin.user.confirmed' }
        NewsLetter:
            class: App\Entity\NewsLetter
            label: 'NewsLetter'
            list:
                actions: [-edit]
                fields:
                  - { property: 'id', label: 'easyAdmin.user.id' }
                  - { property: 'dueAt', label: 'Termin' }
                  - { property: 'sendAt', label: 'Versand' }
                  - { property: 'NoRecipients', label: 'Anzahl' }
                sort: ['dueAt', 'ASC']
            form:
                fields:
                  - { property: 'dueAt', label: 'easyAdmin.user.firstName' }
                  - { property: 'sendAt', label: 'easyAdmin.user.lastName' }
                  - { property: 'NoRecipients', label: 'easyAdmin.user.email' }