monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        mail_logging:
            # log all messages (since debug is the lowest level)
            level:    error
            type:     rotating_file
            path:     '%kernel.logs_dir%/mails.log'
            channels: ["mails"]
            max_files: 10
        grabber_logging:
            # log all messages (since debug is the lowest level)
            level:    error
            type:     rotating_file
            path:     '%kernel.logs_dir%/grabber.log'
            channels: ["grabber"]
            max_files: 10
        profile_logging:
            # log all messages (since debug is the lowest level)
            level:    error
            type:     rotating_file
            path:     '%kernel.logs_dir%/profile.log'
            channels: ["profile"]
            max_files: 10
        kgs_logging:
            # log all messages (since debug is the lowest level)
            level:    error
            type:     stream
            path:     '%kernel.logs_dir%/kgsArchives.log'
            channels: ["kgsArchives"]